version: '3.7'

services:

  finroc:
    image: nkay08/finroc_deps
#    build: .
    container_name: finroc_deps
    volumes:
      - /home/finroc-shared/finroc_user:/home/finroc_user
      - /etc/localtime:/etc/localtime:ro
